version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "433:433"
        volumes:
            - ./src:/var/www
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - code-network
    php:
        image: php:fpm
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
