apiVersion: v1
kind: Pod
metadata:
  name: podinf
spec:
  containers:
    - name: podinfo 
      image: busybox
      command: [ "sh", "-c"]
      args:
      - while true; do
          echo "NODE_NAME=${NODE_NAME}" > /etc/podinfo.txt;
          echo "POD_NAME=${POD_NAME}" >> /etc/podinfo.txt;
          echo "POD_NAMESPACE=${POD_NAMESPACE}" >> /etc/podinfo.txt;
          echo "POD_IP=${POD_IP}" >> /etc/podinfo.txt;
          echo "SERVICE_ACCOUNT=${SERVICE_ACCOUNT}" >> /etc/podinfo.txt;
          sleep 100;
        done;
      volumeMounts:
      - name: podir
        mountPath: /etc
      - name: podinfo
        mountPath: /etc/podinfo.txt
      env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: SERVICE_ACCOUNT
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName
  volumes:
  - name: podir
    hostPath:
      path: /etc
      type: Directory 
  - name: podinfo 
    hostPath:
      path: /etc/podinfo.txt
      type: FileOrCreate
  restartPolicy: Never
