apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: myweb 
    app.kubernetes.io/instance: myweb-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: myweb 
spec:
  selector:
    app: myweb 
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
